from django.urls import path

from . import views


urlpatterns = [
    path("health", views.health),
    path("api/csrf", views.csrf_token),
    path("api/version", views.version),
    path("api/industries", views.industries),
    path("api/sources", views.sources),
    path("api/sources/<str:source_id>", views.source_detail),
    path("api/documents", views.documents),
    path("api/documents/<str:document_id>", views.document_detail),
    path("api/signals", views.signals),
    path("api/signals/extract", views.extract_signal),
    path("api/signals/<str:entity_id>/history", views.signal_history),
    path("api/trends", views.trends),
    path("api/trends/cluster", views.cluster_trend),
    path("api/trends/<str:trend_id>", views.trend_detail),
    path("api/trends/<str:trend_id>/evidence", views.trend_evidence),
    path("api/trends/<str:entity_id>/history", views.trend_history),
    path("api/insights/summary", views.insights_summary),
    path("api/monitoring-rules", views.monitoring_rules),
    path("api/monitoring-rules/<str:rule_id>", views.monitoring_rule_detail),
    path("api/monitoring-rules/<str:rule_id>/run", views.run_monitoring_rule),
    path("api/monitoring-runs", views.monitoring_runs),
    path("api/what-changed-summaries", views.generic_empty),
    path("api/alerts", views.generic_empty),
    path("api/alerts/<str:item_id>", views.generic_empty),
    path("api/strategic-contexts", views.strategic_contexts),
    path("api/assumptions", views.generic_empty),
    path("api/assumptions/<str:item_id>", views.generic_empty),
    path("api/leading-indicators", views.generic_empty),
    path("api/leading-indicators/<str:item_id>", views.generic_empty),
    path("api/strategic-implications", views.generic_empty),
    path("api/scenarios", views.generic_empty),
    path("api/strategic-options", views.generic_empty),
    path("api/strategic-options/<str:item_id>", views.generic_empty),
    path("api/decision-briefs", views.generic_empty),
    path("api/roadmap-items", views.generic_empty),
    path("api/roadmap-items/<str:item_id>", views.generic_empty),
    path("api/source-snapshots", views.generic_empty),
    path("api/source-snapshots/<str:source_id>", views.source_snapshots_for_source),
    path("api/change-events", views.generic_empty),
    path("api/trends/<str:trend_id>/score-history", views.score_history),
    path("api/trends/<str:trend_id>/score-snapshots", views.generic_empty),
    path("api/agent/activities", views.generic_empty),
    path("api/agents/extract/<str:document_id>", views.agent_extract),
    path("api/agent/predictions", views.generic_empty),
    path("api/agent/debates", views.generic_empty),
    path("api/knowledge/nodes", views.generic_empty),
    path("api/knowledge/edges", views.generic_empty),
    path("api/import/sources", views.import_sources),
    path("api/import/documents", views.import_documents),
    path("api/documents/extract-from-sources", views.extract_documents_from_sources),
    path("api/admin/data-health", views.data_health),
    path("api/search/semantic", views.search_semantic),
    path("api/export/trend/<str:trend_id>", views.export_trend),
    path("api/export/industry/<str:industry_id>", views.export_industry),
    path("api/knowledge/trends/<str:trend_id>/build", views.build_knowledge_graph),
    path("api/knowledge/neighborhood/<str:entity_id>", views.knowledge_neighborhood),
    path("api/sources/<str:source_id>/reliability", views.source_reliability),
    path("api/agent/predictions/calibration", views.prediction_calibration),
    path("api/agent/predictions/<str:prediction_id>/calibration", views.prediction_calibration),
]
