"""add_missing_industry_columns

Revision ID: 053eb490af96
Revises: 9a12f03d4b6c
Create Date: 2026-07-03 07:21:00.461709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053eb490af96'
down_revision: Union[str, Sequence[str], None] = '9a12f03d4b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relevance_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategic_priorities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('customer_segments', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('competitors', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('time_horizons', sa.JSON(), nullable=True))

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction_statement', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('target_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('impact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('assumptions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('indicators', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evidence_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.drop_column('early_indicators')
        batch_op.drop_column('likelihood_score')
        batch_op.drop_column('drivers')
        batch_op.drop_column('horizon')
        batch_op.drop_column('dependencies')
        batch_op.drop_column('critical_assumptions')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critical_assumptions', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('dependencies', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('horizon', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('drivers', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('likelihood_score', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('early_indicators', sa.TEXT(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('evidence_ids')
        batch_op.drop_column('indicators')
        batch_op.drop_column('assumptions')
        batch_op.drop_column('impact')
        batch_op.drop_column('target_date')
        batch_op.drop_column('prediction_statement')

    with op.batch_alter_table('industries', schema=None) as batch_op:
        batch_op.drop_column('time_horizons')
        batch_op.drop_column('competitors')
        batch_op.drop_column('customer_segments')
        batch_op.drop_column('strategic_priorities')

    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_column('relevance_reason')
        batch_op.drop_column('quote')


    # ### end Alembic commands ###
