"""Add Phase 5 infrastructure models

Revision ID: 4b99a32f53e7
Revises: 10047b135e6f
Create Date: 2026-06-28 21:21:56.125020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b99a32f53e7'
down_revision: Union[str, Sequence[str], None] = '10047b135e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_role', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_exports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('vector_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('trigger_conditions', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('implications', sa.Text(), nullable=True),
    sa.Column('probability_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('early_warning_indicators', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategic_contexts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('industry_profile_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('business_model', sa.String(), nullable=True),
    sa.Column('target_customers', sa.Text(), nullable=True),
    sa.Column('strategic_goals', sa.Text(), nullable=True),
    sa.Column('current_capabilities', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('risk_appetite', sa.String(), nullable=True),
    sa.Column('planning_horizons', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategic_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('option_type', sa.String(), nullable=True),
    sa.Column('linked_trend_ids', sa.Text(), nullable=True),
    sa.Column('linked_scenario_ids', sa.Text(), nullable=True),
    sa.Column('linked_assumption_ids', sa.Text(), nullable=True),
    sa.Column('expected_benefits', sa.Text(), nullable=True),
    sa.Column('key_risks', sa.Text(), nullable=True),
    sa.Column('required_capabilities', sa.Text(), nullable=True),
    sa.Column('estimated_effort', sa.String(), nullable=True),
    sa.Column('time_to_value', sa.String(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('feasibility_score', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('recommended_next_step', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trends',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('likelihood_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('maturity_stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_debates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.Column('consensus_summary', sa.Text(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.String(), nullable=True),
    sa.Column('related_signal_ids', sa.Text(), nullable=True),
    sa.Column('related_document_ids', sa.Text(), nullable=True),
    sa.Column('related_source_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assumptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('assumption_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('related_signal_ids', sa.Text(), nullable=True),
    sa.Column('related_indicator_ids', sa.Text(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategic_context_id', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('top_opportunities', sa.Text(), nullable=True),
    sa.Column('top_threats', sa.Text(), nullable=True),
    sa.Column('recommended_options', sa.Text(), nullable=True),
    sa.Column('assumptions_to_test', sa.Text(), nullable=True),
    sa.Column('indicators_to_monitor', sa.Text(), nullable=True),
    sa.Column('evidence_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategic_context_id'], ['strategic_contexts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('industry_profile_id', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('enabled', sa.String(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('include_patterns', sa.Text(), nullable=True),
    sa.Column('exclude_patterns', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('likelihood_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('drivers', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('critical_assumptions', sa.Text(), nullable=True),
    sa.Column('early_indicators', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategic_option_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('success_metric', sa.String(), nullable=True),
    sa.Column('linked_indicator_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategic_option_id'], ['strategic_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategic_implications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=False),
    sa.Column('implication_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('affected_capabilities', sa.Text(), nullable=True),
    sa.Column('affected_customer_segments', sa.Text(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leading_indicators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assumption_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('indicator_type', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('threshold', sa.String(), nullable=True),
    sa.Column('monitoring_question', sa.String(), nullable=True),
    sa.Column('related_source_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('documents_scanned', sa.Float(), nullable=True),
    sa.Column('new_documents_found', sa.Float(), nullable=True),
    sa.Column('updated_documents_found', sa.Float(), nullable=True),
    sa.Column('new_signals_found', sa.Float(), nullable=True),
    sa.Column('affected_trend_ids', sa.Text(), nullable=True),
    sa.Column('alert_ids', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['monitoring_rules.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('pestle_category', sa.String(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('strength_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('what_changed_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('monitoring_run_id', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('new_signals', sa.Text(), nullable=True),
    sa.Column('changed_trends', sa.Text(), nullable=True),
    sa.Column('new_candidate_trends', sa.Text(), nullable=True),
    sa.Column('alerts', sa.Text(), nullable=True),
    sa.Column('recommended_actions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['monitoring_run_id'], ['monitoring_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('what_changed_summaries')
    op.drop_table('evidence_links')
    op.drop_table('signals')
    op.drop_table('monitoring_runs')
    op.drop_table('leading_indicators')
    op.drop_table('strategic_implications')
    op.drop_table('roadmap_items')
    op.drop_table('predictions')
    op.drop_table('monitoring_rules')
    op.drop_table('knowledge_edges')
    op.drop_table('documents')
    op.drop_table('decision_briefs')
    op.drop_table('assumptions')
    op.drop_table('alerts')
    op.drop_table('agent_debates')
    op.drop_table('trends')
    op.drop_table('strategic_options')
    op.drop_table('strategic_contexts')
    op.drop_table('sources')
    op.drop_table('scenarios')
    op.drop_table('knowledge_nodes')
    op.drop_table('industries')
    op.drop_table('health_checks')
    op.drop_table('embeddings')
    op.drop_table('data_exports')
    op.drop_table('audit_events')
    op.drop_table('agent_activities')
    # ### end Alembic commands ###
