"""Add extracted enum

Revision ID: d70af3cde133
Revises: 053eb490af96
Create Date: 2026-07-03 10:13:43.112078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70af3cde133'
down_revision: Union[str, Sequence[str], None] = '053eb490af96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kg_nodes',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.Text(), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('kg_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_ids', sa.Text(), nullable=True),
    sa.Column('properties', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['kg_nodes.entity_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['kg_nodes.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('document_fingerprints', sa.Text(), nullable=True),
    sa.Column('raw_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_score_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('likelihood_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('maturity_stage', sa.String(), nullable=True),
    sa.Column('evidence_count', sa.Float(), nullable=True),
    sa.Column('signal_count', sa.Float(), nullable=True),
    sa.Column('source_diversity', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('previous_snapshot_id', sa.String(), nullable=True),
    sa.Column('current_snapshot_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['source_snapshots.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['source_snapshots.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_updates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('update_text', sa.String(), nullable=False),
    sa.Column('confidence_shift', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_score_changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trend_id', sa.String(), nullable=False),
    sa.Column('previous_snapshot_id', sa.String(), nullable=False),
    sa.Column('current_snapshot_id', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('likelihood_delta', sa.Float(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('impact_delta', sa.Float(), nullable=True),
    sa.Column('new_confidence_score', sa.Float(), nullable=True),
    sa.Column('new_momentum_score', sa.Float(), nullable=True),
    sa.Column('new_impact_score', sa.Float(), nullable=True),
    sa.Column('primary_reason', sa.String(), nullable=True),
    sa.Column('horizon_changed', sa.String(), nullable=True),
    sa.Column('maturity_changed', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('related_signal_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['current_snapshot_id'], ['trend_score_snapshots.id'], ),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['trend_score_snapshots.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trends.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('knowledge_edges')
    op.drop_table('knowledge_nodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('node_type', sa.VARCHAR(), nullable=False),
    sa.Column('properties', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_edges',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('source_node_id', sa.VARCHAR(), nullable=False),
    sa.Column('target_node_id', sa.VARCHAR(), nullable=False),
    sa.Column('relationship_type', sa.VARCHAR(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('properties', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('trend_score_changes')
    op.drop_table('prediction_updates')
    op.drop_table('prediction_outcomes')
    op.drop_table('change_events')
    op.drop_table('trend_score_snapshots')
    op.drop_table('source_snapshots')
    op.drop_table('kg_edges')
    op.drop_table('kg_nodes')
    # ### end Alembic commands ###
