import { seedTestData } from "./testSeed";
// @ts-nocheck
import { render, screen, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import { describe, it, expect, beforeEach, vi } from 'vitest';
import SignalsScreen from './SignalsScreen';
import { resetMockData, clearDynamicData, saveDocuments, saveSignals } from './mockRepository';
import { repository } from './repository';

describe('SignalsScreen', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    resetMockData();
    seedTestData(); clearDynamicData();
  });

  const seedReviewableDocument = () => {
    saveDocuments([
      {
        id: 'doc-2',
        sourceId: 'src-2',
        title: 'Approved grocery evidence',
        url: 'https://approved.com/doc2',
        publishedDate: '2026-01-01',
        content: 'Grocery retailers are using AI-assisted discovery and shopping assistants to improve product search and basket building.',
        ingestionStatus: 'extracted',
        extractedSignalIds: [],
      },
    ]);
  };

  it('renders Signals Screen and Generate Trends button', async () => {
    render(<SignalsScreen />);
    expect(await screen.findByRole('heading', { name: 'Extracted Signals' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /generate candidate trends/i })).toBeInTheDocument();
  });

  it('disables trend generation when no signals exist', async () => {
    render(<SignalsScreen />);
    const generateBtn = screen.getByRole('button', { name: /generate candidate trends/i });
    expect(generateBtn).toBeDisabled();
    expect(await screen.findByText(/No signals match current filters/i)).toBeInTheDocument();
  });

  it('generates trends successfully when valid signals are present', async () => {
    // Seed a valid signal that matches a cluster
    seedReviewableDocument();
    saveSignals([
      {
        id: 'sig-1',
        documentId: 'doc-2',
        sourceId: 'src-2',
        title: 'AI-assisted shopping',
        summary: 'Detected AI assistance.',
        signalType: 'AI-assisted shopping',
        pestleCategory: 'Technology',
        noveltyScore: 0.9,
        strengthScore: 0.9,
        confidenceScore: 0.9,
        evidenceDate: '2026-01-01',
        tags: [],
      }
    ]);
    const analyzeSpy = vi.spyOn(repository, 'analyzeTrends').mockResolvedValue([
      {
        id: 'trend-current-run',
        name: 'AI-assisted grocery discovery',
        summary: 'Generated from current evidence.',
        status: 'candidate',
        horizon: '12-24 months',
        likelihoodScore: 0.8,
        confidenceScore: 0.8,
        impactScore: 0.8,
        maturityStage: 'emerging',
        relatedSignalIds: ['sig-1'],
        drivers: [],
        blockers: [],
        whatNeedsToBeTrue: [],
        leadingIndicators: [],
        monitoringQuestions: [],
        recommendedActions: [],
        createdAt: '2026-01-01',
        updatedAt: '2026-01-01',
      }
    ]);

    render(<SignalsScreen />);
    
    // Check signal is rendered
    expect(await screen.findByText(/AI-assisted shopping/i)).toBeInTheDocument();

    const generateBtn = screen.getByRole('button', { name: /generate candidate trends/i });
    fireEvent.click(generateBtn);

    expect(await screen.findByText(/Generated 1 candidate trend from the current evidence run/i)).toBeInTheDocument();
    expect(analyzeSpy).toHaveBeenCalled();
  });
  it('uses backend analysis instead of client-side trend and evidence saving', async () => {
    // Seed a valid signal that matches a cluster
    seedReviewableDocument();
    saveSignals([
      {
        id: 'sig-test-ev',
        documentId: 'doc-2',
        sourceId: 'src-2',
        title: 'AI-assisted shopping',
        summary: 'Detected AI assistance.',
        signalType: 'AI-assisted shopping',
        pestleCategory: 'Technology',
        noveltyScore: 0.9,
        strengthScore: 0.9,
        confidenceScore: 0.9,
        evidenceDate: '2026-01-01',
        tags: [],
      }
    ]);

    const analyzeSpy = vi.spyOn(repository, 'analyzeTrends').mockResolvedValue([
      {
        id: 'new-server-id-123',
        name: 'AI-assisted grocery discovery',
        summary: 'Generated by backend.',
        status: 'candidate',
        horizon: '12-24 months',
        likelihoodScore: 0.8,
        confidenceScore: 0.8,
        impactScore: 0.8,
        maturityStage: 'emerging',
        relatedSignalIds: ['sig-test-ev'],
        drivers: [],
        blockers: [],
        whatNeedsToBeTrue: [],
        leadingIndicators: [],
        monitoringQuestions: [],
        recommendedActions: [],
        createdAt: '2026-01-01',
        updatedAt: '2026-01-01',
      }
    ]);
    const saveTrendsSpy = vi.spyOn(repository, 'saveTrends');
    const addEvidenceSpy = vi.spyOn(repository, 'addEvidence').mockResolvedValue(undefined);

    render(<SignalsScreen />);
    
    const signals = await screen.findAllByText(/AI-assisted shopping/i);
    expect(signals.length).toBeGreaterThan(0);

    const generateBtn = screen.getByRole('button', { name: /generate candidate trends/i });
    fireEvent.click(generateBtn);

    expect(await screen.findByText(/Generated 1 candidate trend/i)).toBeInTheDocument();
    expect(analyzeSpy).toHaveBeenCalled();
    expect(saveTrendsSpy).not.toHaveBeenCalled();
    expect(addEvidenceSpy).not.toHaveBeenCalled();
  });
});
