# Generated by Django 5.1.3 on 2026-07-04 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentActivity",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_role", models.CharField(max_length=255)),
                ("task_type", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "related_entity_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "agent_activities",
            },
        ),
        migrations.CreateModel(
            name="Assumption",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statement", models.CharField(max_length=255)),
                ("assumption_type", models.CharField(max_length=255)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("importance_score", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("related_signal_ids", models.TextField(blank=True, null=True)),
                ("related_indicator_ids", models.TextField(blank=True, null=True)),
                ("evidence_summary", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "assumptions",
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("action", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=255)),
                ("entity_id", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "audit_events",
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation_type", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("file_url", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "data_exports",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "documents",
            },
        ),
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=255)),
                ("entity_id", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("text_content", models.TextField(blank=True, null=True)),
                ("vector_data", models.TextField()),
                ("metadata_json", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "embeddings",
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "health_checks",
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("geography", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "strategic_priorities",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "customer_segments",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("competitors", models.JSONField(blank=True, default=list, null=True)),
                (
                    "time_horizons",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "industries",
            },
        ),
        migrations.CreateModel(
            name="KgNode",
            fields=[
                (
                    "entity_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                ("node_type", models.CharField(max_length=255)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("evidence_ids", models.TextField(blank=True, null=True)),
                ("properties", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "kg_nodes",
            },
        ),
        migrations.CreateModel(
            name="MonitoringRule",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("industry_profile_id", models.CharField(max_length=255)),
                ("frequency", models.CharField(blank=True, max_length=255, null=True)),
                ("enabled", models.CharField(blank=True, max_length=255, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("include_patterns", models.TextField(blank=True, null=True)),
                ("exclude_patterns", models.TextField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "monitoring_rules",
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prediction_statement", models.CharField(max_length=255)),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                ("impact", models.CharField(blank=True, max_length=255, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("assumptions", models.TextField(blank=True, null=True)),
                ("indicators", models.TextField(blank=True, null=True)),
                ("evidence_ids", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "predictions",
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("horizon", models.CharField(blank=True, max_length=255, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("scenario_type", models.CharField(max_length=255)),
                ("trigger_conditions", models.TextField(blank=True, null=True)),
                ("assumptions", models.TextField(blank=True, null=True)),
                ("implications", models.TextField(blank=True, null=True)),
                ("probability_score", models.FloatField(blank=True, null=True)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("early_warning_indicators", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "scenarios",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("credibility_score", models.FloatField(blank=True, null=True)),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                ("freshness_score", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sources",
            },
        ),
        migrations.CreateModel(
            name="StrategicContext",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("industry_profile_id", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "business_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("target_customers", models.TextField(blank=True, null=True)),
                ("strategic_goals", models.TextField(blank=True, null=True)),
                ("current_capabilities", models.TextField(blank=True, null=True)),
                ("constraints", models.TextField(blank=True, null=True)),
                (
                    "risk_appetite",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("planning_horizons", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "strategic_contexts",
            },
        ),
        migrations.CreateModel(
            name="StrategicOption",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "option_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("linked_trend_ids", models.TextField(blank=True, null=True)),
                ("linked_scenario_ids", models.TextField(blank=True, null=True)),
                ("linked_assumption_ids", models.TextField(blank=True, null=True)),
                ("expected_benefits", models.TextField(blank=True, null=True)),
                ("key_risks", models.TextField(blank=True, null=True)),
                ("required_capabilities", models.TextField(blank=True, null=True)),
                (
                    "estimated_effort",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "time_to_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("feasibility_score", models.FloatField(blank=True, null=True)),
                ("urgency_score", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("priority_score", models.FloatField(blank=True, null=True)),
                (
                    "recommended_next_step",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "strategic_options",
            },
        ),
        migrations.CreateModel(
            name="Trend",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("horizon", models.CharField(blank=True, max_length=255, null=True)),
                ("likelihood_score", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                (
                    "maturity_stage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_signal_ids",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("drivers", models.JSONField(blank=True, default=list, null=True)),
                ("blockers", models.JSONField(blank=True, default=list, null=True)),
                (
                    "what_needs_to_be_true",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "leading_indicators",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "monitoring_questions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "recommended_actions",
                    models.JSONField(blank=True, default=list, null=True),
                ),
            ],
            options={
                "db_table": "trends",
            },
        ),
        migrations.CreateModel(
            name="KgEdge",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relationship_type", models.CharField(max_length=255)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("evidence_ids", models.TextField(blank=True, null=True)),
                ("properties", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.kgnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="kgedges_target_set",
                        to="trendmap_api.kgnode",
                    ),
                ),
            ],
            options={
                "db_table": "kg_edges",
            },
        ),
        migrations.CreateModel(
            name="LeadingIndicator",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "indicator_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "current_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("threshold", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "monitoring_question",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("related_source_ids", models.TextField(blank=True, null=True)),
                (
                    "assumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.assumption",
                    ),
                ),
            ],
            options={
                "db_table": "leading_indicators",
            },
        ),
        migrations.CreateModel(
            name="PredictionOutcome",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resolution", models.CharField(max_length=255)),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                ("lessons_learned", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.prediction",
                    ),
                ),
            ],
            options={
                "db_table": "prediction_outcomes",
            },
        ),
        migrations.CreateModel(
            name="PredictionUpdate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("update_text", models.CharField(max_length=255)),
                ("confidence_shift", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.prediction",
                    ),
                ),
            ],
            options={
                "db_table": "prediction_updates",
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "signal_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pestle_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("novelty_score", models.FloatField(blank=True, null=True)),
                ("strength_score", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("evidence_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.document",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.source",
                    ),
                ),
            ],
            options={
                "db_table": "signals",
            },
        ),
        migrations.CreateModel(
            name="MonitoringRun",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("documents_scanned", models.FloatField(blank=True, null=True)),
                ("new_documents_found", models.FloatField(blank=True, null=True)),
                ("updated_documents_found", models.FloatField(blank=True, null=True)),
                ("new_signals_found", models.FloatField(blank=True, null=True)),
                ("affected_trend_ids", models.TextField(blank=True, null=True)),
                ("alert_ids", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.monitoringrule",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.source",
                    ),
                ),
            ],
            options={
                "db_table": "monitoring_runs",
            },
        ),
        migrations.AddField(
            model_name="monitoringrule",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="trendmap_api.source"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="trendmap_api.source"
            ),
        ),
        migrations.CreateModel(
            name="SourceSnapshot",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("document_fingerprints", models.TextField(blank=True, null=True)),
                ("raw_metadata", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.source",
                    ),
                ),
            ],
            options={
                "db_table": "source_snapshots",
            },
        ),
        migrations.CreateModel(
            name="ChangeEvent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("change_type", models.CharField(max_length=255)),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.document",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.source",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="changeevents_current_snapshot_set",
                        to="trendmap_api.sourcesnapshot",
                    ),
                ),
                (
                    "previous_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.sourcesnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "change_events",
            },
        ),
        migrations.CreateModel(
            name="DecisionBrief",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("headline", models.CharField(blank=True, max_length=255, null=True)),
                ("executive_summary", models.TextField(blank=True, null=True)),
                ("top_opportunities", models.TextField(blank=True, null=True)),
                ("top_threats", models.TextField(blank=True, null=True)),
                ("recommended_options", models.TextField(blank=True, null=True)),
                ("assumptions_to_test", models.TextField(blank=True, null=True)),
                ("indicators_to_monitor", models.TextField(blank=True, null=True)),
                ("evidence_ids", models.TextField(blank=True, null=True)),
                (
                    "strategic_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.strategiccontext",
                    ),
                ),
            ],
            options={
                "db_table": "decision_briefs",
            },
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("horizon", models.CharField(blank=True, max_length=255, null=True)),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "success_metric",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("linked_indicator_ids", models.TextField(blank=True, null=True)),
                (
                    "strategic_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.strategicoption",
                    ),
                ),
            ],
            options={
                "db_table": "roadmap_items",
            },
        ),
        migrations.CreateModel(
            name="StrategicImplication",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("implication_type", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                ("affected_capabilities", models.TextField(blank=True, null=True)),
                ("affected_customer_segments", models.TextField(blank=True, null=True)),
                ("urgency_score", models.FloatField(blank=True, null=True)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("evidence_ids", models.TextField(blank=True, null=True)),
                (
                    "trend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.trend",
                    ),
                ),
            ],
            options={
                "db_table": "strategic_implications",
            },
        ),
        migrations.AddField(
            model_name="prediction",
            name="trend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="trendmap_api.trend"
            ),
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relationship_type", models.CharField(max_length=255)),
                ("quote", models.TextField(blank=True, null=True)),
                ("relevance_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.document",
                    ),
                ),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.signal",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.source",
                    ),
                ),
                (
                    "trend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.trend",
                    ),
                ),
            ],
            options={
                "db_table": "evidence_links",
            },
        ),
        migrations.AddField(
            model_name="assumption",
            name="trend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="trendmap_api.trend"
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("alert_type", models.CharField(max_length=255)),
                ("severity", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("related_signal_ids", models.TextField(blank=True, null=True)),
                ("related_document_ids", models.TextField(blank=True, null=True)),
                ("related_source_ids", models.TextField(blank=True, null=True)),
                (
                    "trend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.trend",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
            },
        ),
        migrations.CreateModel(
            name="AgentDebate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("messages", models.TextField(blank=True, null=True)),
                ("consensus_summary", models.TextField(blank=True, null=True)),
                ("confidence_delta", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "trend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.trend",
                    ),
                ),
            ],
            options={
                "db_table": "agent_debates",
            },
        ),
        migrations.CreateModel(
            name="TrendScoreSnapshot",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("likelihood_score", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("momentum_score", models.FloatField(blank=True, null=True)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("horizon", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "maturity_stage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("evidence_count", models.FloatField(blank=True, null=True)),
                ("signal_count", models.FloatField(blank=True, null=True)),
                ("source_diversity", models.FloatField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "trend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.trend",
                    ),
                ),
            ],
            options={
                "db_table": "trend_score_snapshots",
            },
        ),
        migrations.CreateModel(
            name="TrendScoreChange",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("changed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("likelihood_delta", models.FloatField(blank=True, null=True)),
                ("confidence_delta", models.FloatField(blank=True, null=True)),
                ("impact_delta", models.FloatField(blank=True, null=True)),
                ("new_confidence_score", models.FloatField(blank=True, null=True)),
                ("new_momentum_score", models.FloatField(blank=True, null=True)),
                ("new_impact_score", models.FloatField(blank=True, null=True)),
                (
                    "primary_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "horizon_changed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "maturity_changed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("related_signal_ids", models.TextField(blank=True, null=True)),
                (
                    "trend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.trend",
                    ),
                ),
                (
                    "current_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="trendscorechanges_current_snapshot_set",
                        to="trendmap_api.trendscoresnapshot",
                    ),
                ),
                (
                    "previous_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.trendscoresnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "trend_score_changes",
            },
        ),
        migrations.CreateModel(
            name="WhatChangedSummary",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("headline", models.CharField(max_length=255)),
                ("new_signals", models.TextField(blank=True, null=True)),
                ("changed_trends", models.TextField(blank=True, null=True)),
                ("new_candidate_trends", models.TextField(blank=True, null=True)),
                ("alerts", models.TextField(blank=True, null=True)),
                ("recommended_actions", models.TextField(blank=True, null=True)),
                (
                    "monitoring_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="trendmap_api.monitoringrun",
                    ),
                ),
            ],
            options={
                "db_table": "what_changed_summaries",
            },
        ),
    ]
