# Generated by Codex on 2026-07-11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trendmap_api", "0003_news_scanning"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendTheme",
            fields=[
                ("id", models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("keywords", models.JSONField(blank=True, default=list, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("origin", models.CharField(blank=True, max_length=255, null=True)),
                ("evidence_summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("industry", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="trendmap_api.industry")),
            ],
            options={
                "db_table": "trend_themes",
            },
        ),
    ]
