# Generated by Codex on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trendmap_api", "0004_trend_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="url",
            field=models.TextField(),
        ),
    ]
