# Generated by Django 5.1.3 on 2026-07-14 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trendmap_api", "0005_long_evidence_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("finding_type", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                ("why_it_matters", models.TextField(blank=True, null=True)),
                ("evidence_snippet", models.TextField(blank=True, null=True)),
                ("recommended_action", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("discovered_at", models.DateTimeField(blank=True, null=True)),
                ("evidence_date", models.DateTimeField(blank=True, null=True)),
                ("retrieved_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "findings",
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True, null=True)),
                (
                    "owner_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "workspaces",
            },
        ),
        migrations.AddField(
            model_name="finding",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.document",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.signal",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.source",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="trend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.trend",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="industry",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="newsscanrun",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="newssnippet",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="trend",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="trendtheme",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
    ]
