# Generated by Django 5.1.3 on 2026-07-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trendmap_api",
            "0006_finding_workspace_remove_document_documents_run_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="metadata_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="trendtheme",
            name="aliases",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
