# Generated by Django 5.1.3 on 2026-07-14 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trendmap_api", "0007_finding_metadata_json_trendtheme_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategicoption",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="trendmap_api.workspace",
            ),
        ),
    ]
