# Generated by Django 5.1.3 on 2026-07-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trendmap_api", "0009_roadmapitem_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapitem",
            name="last_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="progress_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="progress_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roadmapitem",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
